FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# primeiro-teste

Primeiro teste usando Apiary.

## Hello [/name]
Just one object with one property **name** for very simple Hello application.

### Name [GET]

* Response 200 (application/json)

        {
            "name": "World"
        }